import fs from "fs";
import path from "path";

const baseDir = path.join(process.cwd(), "public/images");
const outputFilePath = path.join(process.cwd(), "app/data.ts");

console.log("🚀 Starting normalization and data generation...");

const catalogData: Record<string, { title: string; files: string[] }> = {};

// 1. Get all category folders
const categories = fs.readdirSync(baseDir);

categories.forEach((category) => {
  const categoryPath = path.join(baseDir, category);

  if (fs.lstatSync(categoryPath).isDirectory()) {
    const files = fs.readdirSync(categoryPath);
    const cleanFiles: string[] = [];

    files.forEach((file) => {
      const oldPath = path.join(categoryPath, file);

      // Normalize filename
      const cleanName = file
        .toLowerCase()
        .replace(/\s+/g, "_")
        .replace(/[()]/g, "")
        .replace(/whatsapp_image_/g, "");

      const newPath = path.join(categoryPath, cleanName);

      // Rename physical file
      if (oldPath !== newPath) {
        fs.renameSync(oldPath, newPath);
      }

      // Store the public path for the frontend
      cleanFiles.push(`/images/${category}/${cleanName}`);
    });

    // Create the object key (e.g., "como_treinar_o_seu_dragao")
    catalogData[category] = {
      title: category
        .replace(/_/g, " ")
        .replace(/\b\w/g, (l) => l.toUpperCase()),
      files: cleanFiles.sort(),
    };
  }
});

// 2. Write the catalogData to a TypeScript file
const fileContent = `// This file is auto-generated by renameFiles.ts. Do not edit manually.
export const CATALOG_DATA = ${JSON.stringify(catalogData, null, 2)} as const;

export type CatalogData = typeof CATALOG_DATA;
`;

fs.writeFileSync(outputFilePath, fileContent);

console.log(`✅ Files normalized and ${outputFilePath} updated!`);
