// This file is auto-generated by renameFiles.ts. Do not edit manually.
export const CATALOG_DATA = {
  "como_treinar_o_seu_dragao": {
    "title": "Como Treinar O Seu Dragao",
    "files": [
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_2.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm_1.jpeg"
    ]
  },
  "dragon_ball": {
    "title": "Dragon Ball",
    "files": [
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_1.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_2.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_3.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.06_pm.jpeg"
    ]
  },
  "flamengo": {
    "title": "Flamengo",
    "files": [
      "/images/flamengo/2026-02-23_at_5.37.31_pm.jpeg",
      "/images/flamengo/2026-02-23_at_5.37.31_pm_1.jpeg",
      "/images/flamengo/2026-02-23_at_5.37.31_pm_2.jpeg",
      "/images/flamengo/2026-02-23_at_5.37.33_pm.jpeg",
      "/images/flamengo/2026-02-23_at_5.37.34_pm.jpeg",
      "/images/flamengo/2026-02-23_at_5.37.35_pm.jpeg",
      "/images/flamengo/whatsapp_video_2026-02-23_at_5.37.32_pm.mp4"
    ]
  },
  "letreiro": {
    "title": "Letreiro",
    "files": [
      "/images/letreiro/2026-02-23_at_5.35.35_pm.jpeg",
      "/images/letreiro/2026-02-23_at_5.35.35_pm_1.jpeg",
      "/images/letreiro/2026-02-23_at_5.35.35_pm_2.jpeg"
    ]
  },
  "miniaturas": {
    "title": "Miniaturas",
    "files": [
      "/images/miniaturas/2026-02-23_at_5.27.38_pm.jpeg",
      "/images/miniaturas/2026-02-23_at_5.27.38_pm_1.jpeg",
      "/images/miniaturas/2026-02-23_at_5.27.38_pm_2.jpeg"
    ]
  },
  "naruto": {
    "title": "Naruto",
    "files": [
      "/images/naruto/2026-02-23_at_5.17.53_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.54_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.54_pm_1.jpeg",
      "/images/naruto/2026-02-23_at_5.17.55_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.56_pm.jpeg"
    ]
  },
  "one_piece": {
    "title": "One Piece",
    "files": [
      "/images/one_piece/2026-02-23_at_5.21.50_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.50_pm_1.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm_1.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm_2.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.52_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.52_pm_1.jpeg"
    ]
  },
  "suporte_cell": {
    "title": "Suporte Cell",
    "files": [
      "/images/suporte_cell/2026-02-23_at_5.28.44_pm.jpeg",
      "/images/suporte_cell/2026-02-23_at_5.28.44_pm_1.jpeg",
      "/images/suporte_cell/2026-02-23_at_5.34.11_pm.jpeg"
    ]
  },
  "suporte_fone": {
    "title": "Suporte Fone",
    "files": [
      "/images/suporte_fone/2026-02-23_at_5.25.25_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.25_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm_2.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm_2.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.28_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.28_pm_1.jpeg"
    ]
  }
} as const;

export type CatalogData = typeof CATALOG_DATA;
