export const projetos = [
  // Como Treinar o Seu Dragão
  {
    id: 1,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 2,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm_1.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 3,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 4,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm_1.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 5,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 6,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_1.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 7,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_2.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 8,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },
  {
    id: 9,
    title: "Como Treinar o Seu Dragão",
    category: "Action Figures",
    image: "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm_1.jpeg",
    description: "Peça impressa em filamento com alto nível de detalhe.",
  },

  // Dragon Ball
  {
    id: 10,
    title: "Dragon Ball",
    category: "Action Figures",
    image: "/images/dragon_ball/2026-02-23_at_5.21.05_pm.jpeg",
    description: "Action figure clássico, ideal para colecionadores.",
  },
  {
    id: 11,
    title: "Dragon Ball",
    category: "Action Figures",
    image: "/images/dragon_ball/2026-02-23_at_5.21.05_pm_1.jpeg",
    description: "Action figure clássico, ideal para colecionadores.",
  },
  {
    id: 12,
    title: "Dragon Ball",
    category: "Action Figures",
    image: "/images/dragon_ball/2026-02-23_at_5.21.05_pm_2.jpeg",
    description: "Action figure clássico, ideal para colecionadores.",
  },
  {
    id: 13,
    title: "Dragon Ball",
    category: "Action Figures",
    image: "/images/dragon_ball/2026-02-23_at_5.21.05_pm_3.jpeg",
    description: "Action figure clássico, ideal para colecionadores.",
  },
  {
    id: 14,
    title: "Dragon Ball",
    category: "Action Figures",
    image: "/images/dragon_ball/2026-02-23_at_5.21.06_pm.jpeg",
    description: "Action figure clássico, ideal para colecionadores.",
  },

  // Enfeites
  {
    id: 19,
    title: "Enfeite Decorativo",
    category: "Decoração",
    image:
      "/images/enfeites/imgi_27_688438846_1619397842695959_2234446570239801672_n.jpg",
    description: "Peça decorativa estilizada para ambientes.",
  },
  {
    id: 20,
    title: "Enfeite Decorativo",
    category: "Decoração",
    image:
      "/images/enfeites/imgi_28_692415708_1624327912176571_983387259885625572_n.jpg",
    description: "Peça decorativa estilizada para ambientes.",
  },
  {
    id: 21,
    title: "Enfeite Decorativo",
    category: "Decoração",
    image:
      "/images/enfeites/imgi_42_656255830_1975545636384650_8338360602485162292_n.jpg",
    description: "Peça decorativa estilizada para ambientes.",
  },
  {
    id: 24,
    title: "Enfeite Decorativo",
    category: "Decoração",
    image: "/images/enfeites/IMG-20260828-WA0102.jpg",
    description: "Peça decorativa estilizada para ambientes.",
  },

  // times
  {
    id: 27,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.31_pm.jpeg",
    description: "Projeto temático exclusivo.",
  },
  {
    id: 28,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.31_pm_1.jpeg",
    description: "Projeto temático exclusivo.",
  },
  {
    id: 29,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.31_pm_2.jpeg",
    description: "Projeto temático exclusivo.",
  },
  {
    id: 30,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.33_pm.jpeg",
    description: "Projeto temático exclusivo.",
  },
  {
    id: 31,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.34_pm.jpeg",
    description: "Projeto temático exclusivo.",
  },
  {
    id: 32,
    title: "Artigo Flamengo",
    category: "Futebol",
    image: "/images/times/2026-02-23_at_5.37.35_pm.jpeg",
    description: "Projeto temático exclusivo.",
  },

  // Letreiro
  {
    id: 33,
    title: "Letreiro",
    category: "Decoração",
    image: "/images/letreiro/2026-02-23_at_5.35.35_pm.jpeg",
    description: "Letreiro customizado para decoração ou comércio.",
  },
  {
    id: 34,
    title: "Letreiro",
    category: "Decoração",
    image: "/images/letreiro/2026-02-23_at_5.35.35_pm_1.jpeg",
    description: "Letreiro customizado para decoração ou comércio.",
  },
  {
    id: 35,
    title: "Letreiro",
    category: "Decoração",
    image: "/images/letreiro/2026-02-23_at_5.35.35_pm_2.jpeg",
    description: "Letreiro customizado para decoração ou comércio.",
  },

  // Miniaturas
  {
    id: 36,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/2026-02-23_at_5.27.38_pm.jpeg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 37,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/2026-02-23_at_5.27.38_pm_1.jpeg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 38,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/2026-02-23_at_5.27.38_pm_2.jpeg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 39,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0057.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 40,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0064.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 41,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0065.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 42,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0075.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 43,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0083.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 44,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0084.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 45,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0093.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 46,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0098.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 47,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0100.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 48,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0119.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 49,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0136.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 50,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0148.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 51,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0150.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },
  {
    id: 52,
    title: "Miniatura Exclusiva",
    category: "Miniaturas",
    image: "/images/miniaturas/IMG-20260828-WA0151.jpg",
    description: "Modelo em escala reduzida com acabamento refinado.",
  },

  // Naruto
  {
    id: 53,
    title: "Naruto Clássico",
    category: "Action Figures",
    image: "/images/naruto/2026-02-23_at_5.17.53_pm.jpeg",
    description: "Modelagem otimizada para impressão limpa em FDM.",
  },
  {
    id: 54,
    title: "Naruto Clássico",
    category: "Action Figures",
    image: "/images/naruto/2026-02-23_at_5.17.54_pm.jpeg",
    description: "Modelagem otimizada para impressão limpa em FDM.",
  },
  {
    id: 55,
    title: "Naruto Clássico",
    category: "Action Figures",
    image: "/images/naruto/2026-02-23_at_5.17.54_pm_1.jpeg",
    description: "Modelagem otimizada para impressão limpa em FDM.",
  },
  {
    id: 56,
    title: "Naruto Clássico",
    category: "Action Figures",
    image: "/images/naruto/2026-02-23_at_5.17.55_pm.jpeg",
    description: "Modelagem otimizada para impressão limpa em FDM.",
  },
  {
    id: 57,
    title: "Naruto Clássico",
    category: "Action Figures",
    image: "/images/naruto/2026-02-23_at_5.17.56_pm.jpeg",
    description: "Modelagem otimizada para impressão limpa em FDM.",
  },

  // One Piece
  {
    id: 58,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.50_pm.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 59,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.50_pm_1.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 60,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.51_pm.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 61,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.51_pm_1.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 62,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.51_pm_2.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 63,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.52_pm.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },
  {
    id: 64,
    title: "Universo One Piece",
    category: "Action Figures",
    image: "/images/one_piece/2026-02-23_at_5.21.52_pm_1.jpeg",
    description: "Design fiel aos personagens da obra original.",
  },

  // Suporte Celular
  {
    id: 97,
    title: "Suporte de Celular",
    category: "Utilitários",
    image: "/images/suporte_cell/2026-02-23_at_5.28.44_pm.jpeg",
    description: "Acessório ergonômico, rígido e durável.",
  },
  {
    id: 98,
    title: "Suporte de Celular",
    category: "Utilitários",
    image: "/images/suporte_cell/2026-02-23_at_5.28.44_pm_1.jpeg",
    description: "Acessório ergonômico, rígido e durável.",
  },
  {
    id: 99,
    title: "Suporte de Celular",
    category: "Utilitários",
    image: "/images/suporte_cell/2026-02-23_at_5.34.11_pm.jpeg",
    description: "Acessório ergonômico, rígido e durável.",
  },

  // Suporte Fone
  {
    id: 100,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.25_pm.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 101,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.25_pm_1.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 102,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.26_pm.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 103,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.26_pm_1.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 104,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.26_pm_2.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 105,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.27_pm.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 106,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.27_pm_1.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 107,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.27_pm_2.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 108,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.28_pm.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },
  {
    id: 109,
    title: "Suporte para Headset",
    category: "Utilitários",
    image: "/images/suporte_fone/2026-02-23_at_5.25.28_pm_1.jpeg",
    description: "Organização e design moderno para o seu setup.",
  },

  // Utilitários Diversos
  {
    id: 110,
    title: "Acessório Utilitário",
    category: "Utilitários",
    image: "/images/utilitarios/IMG-20260828-WA0108.jpg",
    description: "Peça focada em usabilidade e resistência estrutural.",
  },
  {
    id: 111,
    title: "Acessório Utilitário",
    category: "Utilitários",
    image: "/images/utilitarios/IMG-20260828-WA0145.jpg",
    description: "Peça focada em usabilidade e resistência estrutural.",
  },
];
