// This file is auto-generated by renameFiles.ts. Do not edit manually.
export const CATALOG_DATA = {
  "cavaleiros_do_zodiaco": {
    "title": "Cavaleiros Do Zodiaco",
    "files": [
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0058.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0060.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0105.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0123.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0125.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0126.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0130.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0131.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0132.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0133.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0135.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0137.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0140.jpg",
      "/images/cavaleiros_do_zodiaco/img-20260828-wa0149.jpg"
    ]
  },
  "como_treinar_o_seu_dragao": {
    "title": "Como Treinar O Seu Dragao",
    "files": [
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.00_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.01_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.02_pm_2.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm.jpeg",
      "/images/como_treinar_o_seu_dragao/2026-02-23_at_5.17.03_pm_1.jpeg",
      "/images/como_treinar_o_seu_dragao/img-20260828-wa0079.jpg",
      "/images/como_treinar_o_seu_dragao/img-20260828-wa0097.jpg",
      "/images/como_treinar_o_seu_dragao/img-20260828-wa0103.jpg"
    ]
  },
  "dragon_ball": {
    "title": "Dragon Ball",
    "files": [
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_1.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_2.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.05_pm_3.jpeg",
      "/images/dragon_ball/2026-02-23_at_5.21.06_pm.jpeg",
      "/images/dragon_ball/img-20260828-wa0092.jpg"
    ]
  },
  "enfeites": {
    "title": "Enfeites",
    "files": [
      "/images/enfeites/img-20260828-wa0051.jpg",
      "/images/enfeites/img-20260828-wa0056.jpg",
      "/images/enfeites/img-20260828-wa0063.jpg",
      "/images/enfeites/img-20260828-wa0068.jpg",
      "/images/enfeites/img-20260828-wa0102.jpg",
      "/images/enfeites/img-20260828-wa0104.jpg",
      "/images/enfeites/img-20260828-wa0144.jpg",
      "/images/enfeites/imgi_27_688438846_1619397842695959_2234446570239801672_n.jpg",
      "/images/enfeites/imgi_28_692415708_1624327912176571_983387259885625572_n.jpg",
      "/images/enfeites/imgi_42_656255830_1975545636384650_8338360602485162292_n.jpg"
    ]
  },
  "letreiro": {
    "title": "Letreiro",
    "files": [
      "/images/letreiro/2026-02-23_at_5.35.35_pm.jpeg",
      "/images/letreiro/2026-02-23_at_5.35.35_pm_1.jpeg",
      "/images/letreiro/2026-02-23_at_5.35.35_pm_2.jpeg",
      "/images/letreiro/img-20260828-wa0081.jpg",
      "/images/letreiro/img-20260828-wa0082.jpg",
      "/images/letreiro/img-20260828-wa0094.jpg",
      "/images/letreiro/img-20260828-wa0095.jpg",
      "/images/letreiro/img-20260828-wa0096.jpg",
      "/images/letreiro/imgi_30_688028628_17888509401494053_636646819929758826_n.jpg",
      "/images/letreiro/imgi_36_657621742_1388548199970456_5252590927375056941_n.jpg",
      "/images/letreiro/imgi_45_655572303_17882168832494053_4360245894104651563_n.webp"
    ]
  },
  "little_stitch": {
    "title": "Little Stitch",
    "files": [
      "/images/little_stitch/img-20260828-wa0142.jpg"
    ]
  },
  "marvel": {
    "title": "Marvel",
    "files": [
      "/images/marvel/img-20260828-wa0071.jpg",
      "/images/marvel/img-20260828-wa0112.jpg",
      "/images/marvel/img-20260828-wa0138.jpg",
      "/images/marvel/img-20260828-wa0139.jpg",
      "/images/marvel/img-20260828-wa0143.jpg",
      "/images/marvel/img-20260828-wa0146.jpg"
    ]
  },
  "miniaturas": {
    "title": "Miniaturas",
    "files": [
      "/images/miniaturas/2026-02-23_at_5.27.38_pm.jpeg",
      "/images/miniaturas/2026-02-23_at_5.27.38_pm_1.jpeg",
      "/images/miniaturas/2026-02-23_at_5.27.38_pm_2.jpeg",
      "/images/miniaturas/img-20260828-wa0057.jpg",
      "/images/miniaturas/img-20260828-wa0064.jpg",
      "/images/miniaturas/img-20260828-wa0065.jpg",
      "/images/miniaturas/img-20260828-wa0075.jpg",
      "/images/miniaturas/img-20260828-wa0083.jpg",
      "/images/miniaturas/img-20260828-wa0084.jpg",
      "/images/miniaturas/img-20260828-wa0093.jpg",
      "/images/miniaturas/img-20260828-wa0098.jpg",
      "/images/miniaturas/img-20260828-wa0100.jpg",
      "/images/miniaturas/img-20260828-wa0111.jpg",
      "/images/miniaturas/img-20260828-wa0116.jpg",
      "/images/miniaturas/img-20260828-wa0119.jpg",
      "/images/miniaturas/img-20260828-wa0129.jpg",
      "/images/miniaturas/img-20260828-wa0136.jpg",
      "/images/miniaturas/img-20260828-wa0148.jpg",
      "/images/miniaturas/img-20260828-wa0150.jpg",
      "/images/miniaturas/img-20260828-wa0151.jpg",
      "/images/miniaturas/imgi_11_772955244_1006496885704030_7458870294767835411_n.jpg",
      "/images/miniaturas/imgi_18_730773498_1397613275520646_2446017613737875323_n.jpg",
      "/images/miniaturas/imgi_22_714949237_2540483863054219_1737330348286014971_n.jpg",
      "/images/miniaturas/imgi_24_709135140_17892512133494053_7326946971280648329_n.jpg",
      "/images/miniaturas/imgi_37_669831524_17885804919494053_8288662528533974758_n.jpg",
      "/images/miniaturas/imgi_38_671206632_2078586032700633_1121098857454479414_n.jpg",
      "/images/miniaturas/imgi_43_655906402_17882954553494053_4239197587388275489_n.webp",
      "/images/miniaturas/imgi_44_656054417_17882464719494053_7394422431592678924_n.webp",
      "/images/miniaturas/imgi_47_653919343_1400291048506543_5236463422694454465_n.jpg",
      "/images/miniaturas/imgi_48_653024706_17881491063494053_2006531162116490284_n.webp",
      "/images/miniaturas/imgi_49_652802294_17881375386494053_935114678224063399_n.jpg",
      "/images/miniaturas/imgi_50_651779303_1592485915349376_743445844316637640_n.jpg",
      "/images/miniaturas/imgi_51_650489925_17880924885494053_2204371192432273508_n.webp"
    ]
  },
  "naruto": {
    "title": "Naruto",
    "files": [
      "/images/naruto/2026-02-23_at_5.17.53_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.54_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.54_pm_1.jpeg",
      "/images/naruto/2026-02-23_at_5.17.55_pm.jpeg",
      "/images/naruto/2026-02-23_at_5.17.56_pm.jpeg",
      "/images/naruto/imgi_29_684650008_17888993790494053_8243980327536975881_n.jpg",
      "/images/naruto/imgi_46_656621133_17881985097494053_1207530100411080087_n.jpg"
    ]
  },
  "one_piece": {
    "title": "One Piece",
    "files": [
      "/images/one_piece/2026-02-23_at_5.21.50_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.50_pm_1.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm_1.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.51_pm_2.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.52_pm.jpeg",
      "/images/one_piece/2026-02-23_at_5.21.52_pm_1.jpeg",
      "/images/one_piece/img-20260828-wa0109.jpg",
      "/images/one_piece/imgi_34_674526116_17886618570494053_3183464814696119377_n.jpg"
    ]
  },
  "pokemon": {
    "title": "Pokemon",
    "files": [
      "/images/pokemon/img-20260828-wa0078.jpg",
      "/images/pokemon/img-20260828-wa0134.jpg",
      "/images/pokemon/img-20260828-wa0141.jpg",
      "/images/pokemon/imgi_13_754070119_17900860014494053_2803975359714640173_n.jpg",
      "/images/pokemon/imgi_8_787715275_17906287080494053_5249591446145045837_n.jpg"
    ]
  },
  "suporte_cell": {
    "title": "Suporte Cell",
    "files": [
      "/images/suporte_cell/2026-02-23_at_5.28.44_pm.jpeg",
      "/images/suporte_cell/2026-02-23_at_5.28.44_pm_1.jpeg",
      "/images/suporte_cell/2026-02-23_at_5.34.11_pm.jpeg"
    ]
  },
  "suporte_fone": {
    "title": "Suporte Fone",
    "files": [
      "/images/suporte_fone/2026-02-23_at_5.25.25_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.25_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.26_pm_2.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm_1.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.27_pm_2.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.28_pm.jpeg",
      "/images/suporte_fone/2026-02-23_at_5.25.28_pm_1.jpeg"
    ]
  },
  "times": {
    "title": "Times",
    "files": [
      "/images/times/2026-02-23_at_5.37.31_pm.jpeg",
      "/images/times/2026-02-23_at_5.37.31_pm_1.jpeg",
      "/images/times/2026-02-23_at_5.37.31_pm_2.jpeg",
      "/images/times/2026-02-23_at_5.37.33_pm.jpeg",
      "/images/times/2026-02-23_at_5.37.34_pm.jpeg",
      "/images/times/2026-02-23_at_5.37.35_pm.jpeg",
      "/images/times/imgi_21_718221451_17893760649494053_3183179189571667986_n.jpg",
      "/images/times/imgi_32_681592358_927593460114081_1625175522026023288_n.jpg",
      "/images/times/imgi_35_672454668_17886039561494053_2743678423526563720_n.jpg",
      "/images/times/imgi_40_659108366_17884385970494053_8996501646282167823_n.webp",
      "/images/times/imgi_41_658338456_17884382310494053_7527385398873429746_n.webp",
      "/images/times/whatsapp_video_2026-02-23_at_5.37.32_pm.mp4"
    ]
  },
  "utilitarios": {
    "title": "Utilitarios",
    "files": [
      "/images/utilitarios/img-20260828-wa0108.jpg",
      "/images/utilitarios/img-20260828-wa0145.jpg"
    ]
  }
} as const;

export type CatalogData = typeof CATALOG_DATA;
